services:
  capitalflow_client:    
    container_name: capitalflow_client
    environment:
      NODE_ENV: production
    build: 
      context: .
      dockerfile: ./Dockerfile         
    ports:
      - 3002:3002    
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webapp


# volumes:
#   mysql_data:
#   backup:

networks:
  webapp:
    driver: bridge
    external: true

